name: Run NDB CONCHECK

on:
  workflow_dispatch:

jobs:
  run-on-windows:
    runs-on: self-hosted
    steps:
      - name: Run Node script from local path        
        run: node ndb_concheck.loader.js
        working-directory: "D:\\Nokia-IOH\\Personal\\node.js\\ndbconcheck\\dist"
