name: Run NDB Action

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Action profile (e.g., update_bcf, del_mocnstep)'
        required: true
        default: 'update_bcf'
      payload:
        description: 'JSON string of parameters (user input values)'
        required: true
        default: '{"SITE_ID":"14DMK0001","BTS_ID":99,"CELL_SYSTEM_INFO":["GSM900","DCS1800"]}'

jobs:
  run-on-windows:
    runs-on: self-hosted
    steps:
      - name: Prepare payload (base64 encode)
        id: prep
        shell: powershell
        env:
          PAYLOAD: ${{ github.event.inputs.payload }}
        run: |
          # read payload from env to avoid quoting/escaping problems
          $json = $env:PAYLOAD
          if (-not $json) {
            Write-Error "No payload provided in env PAYLOAD"
            exit 1
          }
          # base64 encode
          $b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($json))
          # set as step output
          echo "b64=$b64" >> $env:GITHUB_OUTPUT

      - name: Run Node script from local path
        shell: powershell
        run: |
          Write-Host "Running profile=${{ github.event.inputs.profile }}"
          Write-Host "Payload (preview): $($env:PAYLOAD)"
          node ndbaction.js --profile=${{ github.event.inputs.profile }} --payload-b64 ${{ steps.prep.outputs.b64 }}
        working-directory: "D:\\sqllite"
