name: NDB Action Runner

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "Action profile (e.g., update_bcf, del_mocnstep)"
        required: true
        default: "update_bcf"
      params:
        description: "User parameters in JSON string"
        required: true

jobs:
  run-ndbaction:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ndbaction.js
        run: |
          echo "Running profile: ${{ github.event.inputs.profile }}"
          echo "With params: ${{ github.event.inputs.params }}"
          node ndbaction.js "${{ github.event.inputs.profile }}" "${{ github.event.inputs.params }}"
	      working-directory: "D:\\sqllite"
