name: Run NDB Action

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Action profile (e.g., update_bcf, del_mocnstep)'
        required: true
        default: 'update_bcf'
      params:
        description: 'JSON string of parameters (user input values)'
        required: true
        default: '{"SITE_ID":"14DMK0001","BTS_ID":99,"CELL_SYSTEM_INFO":"GSM900|DCS1800"}'

jobs:
  run-on-windows:
    runs-on: self-hosted
    steps:
      - name: Run Node script from local path
        run: |
          echo Running profile=${{ github.event.inputs.profile }}
          echo Params=${{ github.event.inputs.params }}
          node ndbaction.js --profile ${{ github.event.inputs.profile }} --params '${{ github.event.inputs.params }}'
        working-directory: "D:\\sqllite"
